<?php
$config = [
    'driver' => 'sqlite',
    'live_id' => 12,
    'client_id' => 1008,
    'cod_locatie' => 1,
    'installation_uuid' => 'identificator-unic-instalare',
    'installation_identity_format' => 'restaurant',
    'app_name' => 'App Restaurant Offline',
    'offline_api_path' => dirname(dirname(__DIR__)) . '/api_offline_taverna_amicii',
    'sqlite_path' => dirname(dirname(__DIR__)) . '/api_offline_taverna_amicii/restaurant.sqlite',
    'sync_export_path' => dirname(dirname(__DIR__)) . '/api_offline_taverna_amicii/offline_sync_exports',
    'no_session_validation' => 0,
    'offline_license' => [
        'api_url' => 'https://domeniu.ro/sincronizare_online_app_vanzare/api_verificare_licenta_offline.php',
        'valid_days' => 30,
    ],
    'online_products_sync' => [
        'enabled' => false,
        'auto_check' => false,
        'strict' => true,
        'api_url' => 'https://domeniu.ro/sincronizare_online_app_restaurant/sincronizare_date_offline.php',
        'api_key' => 'CHEIA_CLIENTULUI',
        'cod_client' => 1008,
        'timeout_seconds' => 30,
        'dry_run' => false,
        'rewrite_existing' => false,
        'send_api_key_in_query' => true,
        'verify_ssl' => true,
        'allow_http_without_session' => true,
    ],
    'offline_sales_sync' => [
        'enabled' => false,
        'automatic' => false,
        'allow_login_worker' => false,
        'automatic_interval_seconds' => 120,
        'strict' => true,
        'api_url' => 'https://domeniu.ro/sincronizare_online_app_restaurant/sincronizare_date_offline.php',
        'api_key' => 'CHEIA_CLIENTULUI',
        'timeout_seconds' => 45,
        'send_api_key_in_query' => true,
        'verify_ssl' => true,
        'debug_db' => false,
    ],
    'online_tablet_sync' => [
        'enabled' => false,
        'automatic' => true,
        'automatic_interval_seconds' => 30,
        'api_url' => 'https://domeniu.ro/api/offline-tablet-orders.php',
        'api_key' => 'CHEIA_CLIENTULUI',
        'client_id' => 1008,
        'cod_locatie' => 1,
        'installation_uuid' => 'identificator-unic-instalare',
        'timeout_seconds' => 30,
        'limit' => 200,
        'send_api_key_in_query' => true,
        'verify_ssl' => true,
    ],
];

require_once __DIR__ . '/offline_installation_identity_lib.php';
return offline_installation_identity_apply_config($config);
