<?php
return [
    'driver' => 'sqlite',
    'live_id' => 12,
    'client_id' => 1008,
    'cod_locatie' => 1,
    'installation_uuid' => 'taverna-amicii-1008-l1-20260814',
    'offline_api_path' => dirname(dirname(__DIR__)) . '/api_offline_taverna_amicii',
    'sqlite_path' => dirname(dirname(__DIR__)) . '/api_offline_taverna_amicii/restaurant.sqlite',
    'sync_export_path' => dirname(dirname(__DIR__)) . '/api_offline_taverna_amicii/offline_sync_exports',
    'no_session_validation' => 0,
    'online_products_sync' => [
        'enabled' => true,
        'auto_check' => false,
        'strict' => true,
        'api_url' => 'https://agecs.agecs.in/sincronizare_online_app_restaurant/sincronizare_date_offline.php',
        'api_key' => '99c482812c565c2a7fd757492bb662395f0f1462ff383765eba2b4725f3db54f',
        'cod_client' => 1008,
        'timeout_seconds' => 30,
        'dry_run' => false,
        'rewrite_existing' => false,
        'send_api_key_in_query' => true,
        'verify_ssl' => true,
        'allow_http_without_session' => true,
    ],
    'offline_sales_sync' => [
        'enabled' => true,
        'automatic' => true,
        'allow_login_worker' => true,
        'automatic_interval_seconds' => 120,
        'strict' => true,
        'api_url' => 'https://agecs.agecs.in/sincronizare_online_app_restaurant/sincronizare_date_offline.php',
        'api_key' => '99c482812c565c2a7fd757492bb662395f0f1462ff383765eba2b4725f3db54f',
        'timeout_seconds' => 45,
        'send_api_key_in_query' => true,
        'verify_ssl' => true,
        'debug_db' => false,
    ],
    'online_tablet_sync' => [
        'enabled' => true,
        'automatic' => true,
        'automatic_interval_seconds' => 30,
        'api_url' => 'https://agecs.agecs.in/api/offline-tablet-orders.php',
        'api_key' => '99c482812c565c2a7fd757492bb662395f0f1462ff383765eba2b4725f3db54f',
        'client_id' => 1008,
        'cod_locatie' => 1,
        'installation_uuid' => 'taverna-amicii-1008-l1-20260814',
        'timeout_seconds' => 30,
        'limit' => 200,
        'send_api_key_in_query' => true,
        'verify_ssl' => true,
    ],
];
