<?php require_once __DIR__.'/database_connection.php';
$casaPageInvoice=(int)($_GET['id_factura']??0);
$casaPageMeta=$casaPageInvoice?casa_one($pdo,'SELECT online_id,authority FROM casa_invoices WHERE id_factura=?',[$casaPageInvoice]):null;
?>
<!doctype html><html lang="ro"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="casa-csrf" content="<?=casa_h($_SESSION['casa_csrf'])?>"><title>ECOGEST, Casa Luanna</title>
<link rel="stylesheet" href="vendor/offline/bootstrap4/bootstrap.min.css"><link rel="stylesheet" href="vendor/offline/fontawesome5/css/all.min.css"><link rel="stylesheet" href="vendor/offline/select2/select2.min.css"><link rel="stylesheet" href="vendor/offline/datatables/dataTables.bootstrap4.min.css">
<script src="js/jquery-3.6.0.min.js"></script><script src="vendor/offline/bootstrap4/bootstrap.bundle.min.js"></script><script src="vendor/offline/select2/select2.min.js"></script><script src="vendor/offline/datatables/jquery.dataTables.min.js"></script><script src="vendor/offline/datatables/dataTables.bootstrap4.min.js"></script><script src="offline_ui.js"></script>
<style>body{background:#f4f6f8;color:#253442}nav.casa{display:flex;gap:18px;align-items:center;padding:14px 24px;background:#173d45;color:white;flex-wrap:wrap}nav.casa a{color:white}.container-fluid{padding:24px}.card{margin-bottom:18px}.table td{vertical-align:middle}.select2-container{min-width:180px}#casa-sync{margin-left:auto;font-size:13px}@media print{nav.casa,.casa-actions{display:none}}</style></head><body>
<nav class="casa" data-online-invoice="<?=(int)($casaPageMeta['online_id']??0)?>"><strong>ECOGEST · Casa Luanna</strong><a href="facturi.php">Facturi</a><a href="factura.php">Factură nouă</a><a href="administrare.php">Date firmă și serii</a><a href="sincronizare.php">Sincronizare</a><a href="logout.php">Ieșire</a><span id="casa-sync">Sincronizare automată</span></nav>
<div id="casa-pull-status" class="alert alert-info m-3" role="status">Verificarea online se face în fundal. Lista locală rămâne disponibilă.</div>
